"""Adicionar relacionamento muitos-para-muitos entre services e categories

Revision ID: 302e60a63201
Revises: 4e092ce8ebc6
Create Date: 2025-10-06 20:23:36.939051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302e60a63201'
down_revision = '4e092ce8ebc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_categories')
    # ### end Alembic commands ###
